Update JJWT to version 0.12 (backwards-incompatible) and use Jackson ObjectReader, update other dependencies
web-eid/web-eid-authtoken-validation-java pull request #58
Opened 2024-03-22 17:12 UTC by mrts

Signed-off-by: Mart Somermaa <mrts@users.noreply.github.com>

2024-03-22 17:15 UTC, mrts commented on src/test/java/eu/webeid/security/validator/certvalidators/SubjectCertificateNotRevokedValidatorTest.java
> +// TODO:            .withMessage("User certificate revocation check has failed: OCSP response must contain one response, received 2 responses instead");
This must be fixed. Newer Bouncy Castle checks the certificate more strictly, so the validation breaks before reaching 2 responses.

2024-04-09 07:13 UTC, metsma requested changes

2024-04-09 07:13 UTC, metsma commented on src/test/java/eu/webeid/security/validator/AuthTokenSignatureValidatorTest.java
> +        final WebEidAuthToken authToken = OBJECT_READER.readValue(VALID_AUTH_TOKEN, WebEidAuthToken.class);
```suggestion
        final WebEidAuthToken authToken = OBJECT_READER.readValue(VALID_AUTH_TOKEN);
```

2024-04-09 10:30 UTC, mrts commented on src/test/java/eu/webeid/security/validator/AuthTokenSignatureValidatorTest.java
> +        final WebEidAuthToken authToken = OBJECT_READER.readValue(VALID_AUTH_TOKEN, WebEidAuthToken.class);
Thanks, good catch!

2024-04-09 10:33 UTC, mrts commented on src/test/java/eu/webeid/security/validator/AuthTokenSignatureValidatorTest.java
> +        final WebEidAuthToken authToken = OBJECT_READER.readValue(VALID_AUTH_TOKEN, WebEidAuthToken.class);
Fixed.

2024-04-09 11:00 UTC, metsma approved these changes

2024-04-09 11:35 UTC, merged